#packages installing section run first
install.packages("data.table")
library(data.table)
install.packages("ggplot2")
library(ggplot2)
install.packages("plotly")
library(plotly)
install.packages("knitr")
library(knitr)

---
title: "Stefan Maciolek - Homework 1"
output: 
  html_notebook:
    toc:true
---

```{r setup}
require(data.table)
require(ggplot2)
require(plotly)
require(DT)

N <- 5 # number of animals per group
n_trt <- 5 # number of treatment groups
```

# Data
```{r data_sim}
dt1 <- data.table(Group = rep(c("Naive",
                                 "Vehicle",
                                 "Treatment_1",
                                 "Treatment_2",
                                 "Treatment_3"),
                               each = N),
                  ID = paste0("ID",
                              1:(N*n_trt)),
                  #adding scores up here, unresovalable errors when adding scores below
                  Inflammation_Score = c(rnorm(n = 5, mean = 0, sd = 1),
                                rnorm(n = 5, mean = 5, sd = 1),
                                rnorm(n = 5, mean = 3, sd = 1),
                                rnorm(n = 5, mean = 2, sd = 1),
                                rnorm(n = 5, mean = 4, sd = 1)))
data.table(dt1,
          rownames = FALSE) #there needed to be a . in the function name
```



```{r plot}
#removing the legend, adding a title and subtitle
p1 <- ggplot(data = dt1,
             aes(x = Group,
                 y = Inflammation_Score, #I changed the names to make them more clear
                 fill = ID)) +
  geom_point(shape = 21,
             size = 3,
             position = position_dodge(0.3),show.legend = "false")

p1 <- p1 + labs(title = "Inflammation Scores by Treatment Group",subtitle = "Naive received no inflmmatory agent or treatment. Vehicle received only inflammatory agent. \nTreatments 1, 2, and 3 received inflammatory agent and treatment")
print(p1)

ggplotly(p1)

#adding a qqplot to check variance
qqnorm(dt1$Inflammation_Score)
```

